insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (1, 'Pontiac', 'Grand Prix', 1969);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (2, 'Pontiac', 'Firebird', 1989);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (3, 'Audi', 'A6', 2010);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (4, 'Lexus', 'GX', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (5, 'Suzuki', 'X-90', 1996);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (6, 'Volvo', '240', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (7, 'BMW', '5 Series', 2010);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (8, 'Acura', 'MDX', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (9, 'Saab', '9-5', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (10, 'Ford', 'GT500', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (11, 'Saturn', 'L-Series', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (12, 'Dodge', 'D150', 1992);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (13, 'Pontiac', 'Sunbird', 1989);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (14, 'Toyota', 'Sienna', 2003);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (15, 'Hummer', 'H1', 2001);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (16, 'Saab', '9-5', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (17, 'Chrysler', 'Town & Country', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (18, 'Buick', 'LeSabre', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (19, 'Lexus', 'LX', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (20, 'Hyundai', 'Sonata', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (21, 'GMC', 'Yukon XL 2500', 2010);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (22, 'Volkswagen', 'Eurovan', 1992);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (23, 'Mazda', 'MX-5', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (24, 'Ford', 'Mustang', 2010);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (25, 'GMC', 'Canyon', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (26, 'Porsche', '911', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (27, 'Volkswagen', 'Corrado', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (28, 'Infiniti', 'I', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (29, 'Porsche', 'Boxster', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (30, 'Toyota', 'T100', 1998);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (31, 'Mercedes-Benz', 'R-Class', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (32, 'Mitsubishi', 'Endeavor', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (33, 'Toyota', 'Solara', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (34, 'Volkswagen', 'rio', 1997);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (35, 'Chrysler', 'Cirrus', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (36, 'Dodge', 'Ram', 2003);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (37, 'Nissan', 'Rogue', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (38, 'Pontiac', 'Bonneville', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (39, 'Chevrolet', 'HHR', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (40, 'Acura', 'Integra', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (41, 'Honda', 'Pilot', 2003);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (42, 'Dodge', 'Viper', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (43, 'Dodge', 'Caravan', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (44, 'Pontiac', 'Firebird', 1967);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (45, 'Mercury', 'Sable', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (46, 'Ford', 'Club Wagon', 1997);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (47, 'Pontiac', 'LeMans', 1966);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (48, 'Cadillac', 'Seville', 2003);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (49, 'GMC', 'Safari', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (50, 'Ford', 'LTD Crown Victoria', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (51, 'Hyundai', 'Tiburon', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (52, 'Toyota', 'Avalon', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (53, 'GMC', 'Savana 3500', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (54, 'Chrysler', 'Town & Country', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (55, 'Mazda', 'Mazdaspeed6', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (56, 'Chevrolet', 'Venture', 2004);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (57, 'Toyota', 'MR2', 2003);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (58, 'Volkswagen', 'Fox', 1988);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (59, 'Mercury', 'Mystique', 1997);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (60, 'Ford', 'E-Series', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (61, 'Dodge', 'Intrepid', 1998);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (62, 'Mercedes-Benz', '300TE', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (63, 'Ferrari', 'F430', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (64, 'Buick', 'Regal', 1996);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (65, 'GMC', '2500', 1996);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (66, 'Mitsubishi', 'Montero', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (67, 'Buick', 'Terraza', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (68, 'Lexus', 'LX', 1998);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (69, 'Volkswagen', 'Jetta', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (70, 'Hyundai', 'XG300', 2001);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (71, 'Ford', 'Excursion', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (72, 'Nissan', 'Maxima', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (73, 'Dodge', 'Ram 2500 Club', 1997);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (74, 'Studebaker', 'Avanti', 1964);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (75, 'Acura', 'CL', 2001);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (76, 'Chevrolet', 'G-Series 1500', 1998);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (77, 'Plymouth', 'Laser', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (78, 'Kia', 'Soul', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (79, 'Cadillac', 'Eldorado', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (80, 'Volkswagen', 'Jetta', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (81, 'Hyundai', 'Accent', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (82, 'Jaguar', 'XK Series', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (83, 'Isuzu', 'Rodeo', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (84, 'Mercedes-Benz', 'CLK-Class', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (85, 'GMC', 'Sierra 2500', 2002);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (86, 'Hyundai', 'Tiburon', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (87, 'Aston Martin', 'V8 Vantage', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (88, 'Honda', 'Ridgeline', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (89, 'Ford', 'E-Series', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (90, 'Lexus', 'LS Hybrid', 2010);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (91, 'GMC', 'Yukon', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (92, 'Cadillac', 'CTS', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (93, 'GMC', 'Terrain', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (94, 'Chevrolet', 'Avalanche 1500', 2002);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (95, 'Chevrolet', 'Express 1500', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (96, 'Lotus', 'Elise', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (97, 'Honda', 'FCX Clarity', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (98, 'Maserati', 'Gran Sport', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (99, 'Ford', 'Econoline E250', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (100, 'Plymouth', 'Voyager', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (101, 'Mercury', 'Mountaineer', 2010);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (102, 'Honda', 'Accord', 1988);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (103, 'Chevrolet', 'G-Series G10', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (104, 'Chevrolet', 'Monte Carlo', 1998);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (105, 'Isuzu', 'Ascender', 2004);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (106, 'Ram', '1500', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (107, 'Lincoln', 'MKT', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (108, 'Volvo', 'S60', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (109, 'Volvo', 'XC70', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (110, 'Mercedes-Benz', 'CLS-Class', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (111, 'Lotus', 'Esprit', 2003);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (112, 'Saab', '9-3', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (113, 'Ford', 'Transit Connect', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (114, 'Hyundai', 'Veracruz', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (115, 'Lincoln', 'MKS', 2013);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (116, 'BMW', '525', 2004);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (117, 'Oldsmobile', '88', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (118, 'Chevrolet', 'Express 2500', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (119, 'Mercedes-Benz', 'M-Class', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (120, 'Ford', 'Econoline E250', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (121, 'GMC', 'Yukon', 2002);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (122, 'Ford', 'Laser', 1989);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (123, 'Mitsubishi', 'Galant', 1985);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (124, 'Mercedes-Benz', 'SLK-Class', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (125, 'Lamborghini', 'Diablo', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (126, 'Eagle', 'Summit', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (127, 'McLaren', 'MP4-12C', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (128, 'Oldsmobile', 'Cutlass Cruiser', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (129, 'Honda', 'S2000', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (130, 'Ford', 'Thunderbird', 1997);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (131, 'Hyundai', 'Veracruz', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (132, 'Ford', 'Probe', 1997);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (133, 'Lotus', 'Esprit', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (134, 'Plymouth', 'Acclaim', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (135, 'Ford', 'Thunderbird', 1955);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (136, 'Mitsubishi', 'Montero', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (137, 'Mitsubishi', 'Space', 1984);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (138, 'Dodge', 'Dakota Club', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (139, 'Chevrolet', 'Cobalt SS', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (140, 'Chevrolet', 'G-Series G30', 1996);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (141, 'Audi', 'A8', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (142, 'Mercedes-Benz', 'S-Class', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (143, 'Subaru', 'Alcyone SVX', 1992);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (144, 'Chevrolet', 'G-Series 2500', 1998);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (145, 'Toyota', 'Supra', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (146, 'Pontiac', 'Firebird', 1984);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (147, 'Ford', 'Taurus', 2013);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (148, 'GMC', 'Envoy XL', 2003);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (149, 'Mercedes-Benz', 'M-Class', 1998);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (150, 'Toyota', 'RAV4', 1997);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (151, 'Ford', 'E150', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (152, 'Lincoln', 'Aviator', 2003);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (153, 'GMC', '3500', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (154, 'GMC', 'Savana 1500', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (155, 'Ford', 'Expedition', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (156, 'Volkswagen', 'Rabbit', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (157, 'Volkswagen', 'Passat', 2001);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (158, 'Nissan', 'Cube', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (159, 'Lincoln', 'Continental Mark VII', 1990);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (160, 'Mazda', 'B-Series', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (161, 'Volkswagen', 'Scirocco', 1986);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (162, 'Oldsmobile', 'Achieva', 1992);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (163, 'Dodge', 'Viper', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (164, 'BMW', 'Z4', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (165, 'Saab', '9-5', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (166, 'Ferrari', 'F430', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (167, 'Ram', '1500', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (168, 'Lamborghini', 'Reventón', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (169, 'Subaru', 'Leone', 1985);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (170, 'Mitsubishi', 'Raider', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (171, 'Ford', 'Escort', 2002);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (172, 'Pontiac', 'Sunbird', 1988);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (173, 'Mazda', 'MPV', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (174, 'Dodge', 'Dakota', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (175, 'Ford', 'F-Series Super Duty', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (176, 'Lexus', 'LX', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (177, 'Volkswagen', 'GTI', 2004);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (178, 'Chevrolet', 'Venture', 2004);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (179, 'Volvo', '940', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (180, 'Jaguar', 'XF', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (181, 'Eagle', 'Talon', 1990);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (182, 'GMC', 'Sonoma Club Coupe', 1998);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (183, 'Infiniti', 'G', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (184, 'Suzuki', 'Forenza', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (185, 'Mercury', 'Lynx', 1986);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (186, 'Chevrolet', '3500', 1996);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (187, 'Mercedes-Benz', 'CLK-Class', 2002);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (188, 'Mitsubishi', 'GTO', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (189, 'GMC', '1500', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (190, 'Ford', 'Escape', 2013);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (191, 'Honda', 'Element', 2010);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (192, 'Porsche', 'Cayman', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (193, 'Pontiac', 'Sunfire', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (194, 'Audi', 'A6', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (195, 'Mercury', 'Villager', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (196, 'Suzuki', 'SJ', 1986);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (197, 'Hyundai', 'Tiburon', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (198, 'GMC', '1500 Club Coupe', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (199, 'Toyota', 'Tundra', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (200, 'Toyota', 'Celica', 1992);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (201, 'Infiniti', 'G37', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (202, 'Saturn', 'VUE', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (203, 'Honda', 'Accord', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (204, 'Subaru', 'Outback', 2002);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (205, 'Ford', 'F150', 1992);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (206, 'Morgan', 'Aero 8', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (207, 'Porsche', 'Boxster', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (208, 'Lexus', 'ES', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (209, 'Lincoln', 'Town Car', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (210, 'Mercury', 'Cougar', 1990);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (211, 'Chevrolet', '2500', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (212, 'GMC', 'Yukon XL 2500', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (213, 'Infiniti', 'M', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (214, 'Mitsubishi', 'GTO', 1991);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (215, 'Dodge', 'Nitro', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (216, 'Bentley', 'Arnage', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (217, 'Isuzu', 'Rodeo', 1996);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (218, 'Pontiac', 'Grand Prix', 1971);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (219, 'MINI', 'Cooper Clubman', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (220, 'Pontiac', 'Tempest', 1966);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (221, 'Chevrolet', 'G-Series 3500', 1997);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (222, 'Chevrolet', 'Prizm', 2002);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (223, 'Toyota', 'Avalon', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (224, 'Lexus', 'IS-F', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (225, 'Dodge', 'Ram Van B350', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (226, 'Nissan', 'Quest', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (227, 'Ford', 'Ranger', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (228, 'Oldsmobile', 'Silhouette', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (229, 'Buick', 'Coachbuilder', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (230, 'Ford', 'F250', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (231, 'Mazda', 'MX-5', 1998);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (232, 'Toyota', 'Celica', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (233, 'BMW', '750', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (234, 'BMW', 'Z4', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (235, 'Nissan', 'Pathfinder', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (236, 'Plymouth', 'Grand Voyager', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (237, 'Toyota', 'Matrix', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (238, 'Ford', 'Econoline E150', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (239, 'Saab', '900', 1987);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (240, 'Volkswagen', 'Jetta', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (241, 'Dodge', 'Caravan', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (242, 'Dodge', 'Sprinter', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (243, 'Volvo', '960', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (244, 'Maserati', 'Spyder', 1989);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (245, 'Chevrolet', '3500', 1992);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (246, 'Toyota', 'Camry Hybrid', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (247, 'Chrysler', 'Town & Country', 2002);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (248, 'Oldsmobile', 'Aurora', 2003);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (249, 'Isuzu', 'Trooper', 1998);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (250, 'Toyota', '4Runner', 2010);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (251, 'Volkswagen', 'Scirocco', 1985);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (252, 'Dodge', 'Stratus', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (253, 'Mazda', 'Familia', 1990);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (254, 'Chrysler', '300', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (255, 'Oldsmobile', '88', 1996);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (256, 'Oldsmobile', 'Achieva', 1997);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (257, 'Infiniti', 'Q', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (258, 'Land Rover', 'Range Rover', 1996);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (259, 'Infiniti', 'I', 2002);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (260, 'Bentley', 'Azure', 2010);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (261, 'Morgan', 'Aero 8', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (262, 'Subaru', 'SVX', 1996);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (263, 'Ford', 'E-Series', 1987);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (264, 'Pontiac', 'Sunbird', 1987);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (265, 'Ford', 'Contour', 1998);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (266, 'Ford', 'Thunderbird', 1984);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (267, 'Dodge', 'Dakota Club', 2004);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (268, 'Ford', 'F-Series', 2004);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (269, 'Saab', '9-5', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (270, 'Subaru', 'Forester', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (271, 'Jaguar', 'X-Type', 2002);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (272, 'Isuzu', 'Ascender', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (273, 'Isuzu', 'Trooper', 1998);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (274, 'GMC', '3500', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (275, 'Toyota', 'Land Cruiser', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (276, 'Bentley', 'Continental GTC', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (277, 'Lamborghini', 'Murciélago', 2004);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (278, 'Subaru', 'Legacy', 1991);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (279, 'Ford', 'Econoline E150', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (280, 'Pontiac', 'Daewoo Kalos', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (281, 'Lexus', 'CT', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (282, 'Mazda', 'MPV', 2002);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (283, 'Eagle', 'Talon', 1997);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (284, 'Mercedes-Benz', 'W201', 1985);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (285, 'Ford', 'E350', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (286, 'Audi', 'A5', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (287, 'Porsche', '928', 1990);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (288, 'Chevrolet', 'Volt', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (289, 'Ford', 'Aerostar', 1996);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (290, 'Jaguar', 'XJ', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (291, 'Chevrolet', 'Silverado 3500', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (292, 'Suzuki', 'Grand Vitara', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (293, 'Nissan', 'Altima', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (294, 'BMW', 'X3', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (295, 'Ford', 'Econoline E250', 1992);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (296, 'BMW', '6 Series', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (297, 'Toyota', 'Tundra', 2001);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (298, 'Hyundai', 'Accent', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (299, 'Cadillac', 'Escalade ESV', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (300, 'Chevrolet', 'SSR', 2004);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (301, 'Dodge', 'Ram 1500 Club', 2001);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (302, 'Cadillac', 'SRX', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (303, 'Jaguar', 'X-Type', 2003);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (304, 'Volvo', '940', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (305, 'Mercedes-Benz', 'E-Class', 1992);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (306, 'Dodge', 'Viper', 1998);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (307, 'Audi', 'Coupe GT', 1986);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (308, 'Toyota', 'Camry Hybrid', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (309, 'Scion', 'tC', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (310, 'Toyota', 'Prius', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (311, 'Lincoln', 'Continental', 1984);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (312, 'Cadillac', 'XLR', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (313, 'Chevrolet', 'Express 2500', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (314, 'Suzuki', 'Equator', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (315, 'Volkswagen', 'Scirocco', 1987);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (316, 'Chevrolet', 'Lumina', 1997);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (317, 'Acura', 'Integra', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (318, 'Chevrolet', 'Astro', 2002);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (319, 'Mitsubishi', 'Diamante', 1996);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (320, 'Ford', 'Crown Victoria', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (321, 'Maserati', 'Spyder', 1990);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (322, 'Volvo', 'V70', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (323, 'Kia', 'Optima', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (324, 'Ford', 'F150', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (325, 'Mazda', 'CX-9', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (326, 'Chevrolet', 'Camaro', 2002);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (327, 'Honda', 'Prelude', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (328, 'Ford', 'Focus', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (329, 'Ford', 'Mustang', 1973);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (330, 'Mercury', 'Tracer', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (331, 'Mercedes-Benz', 'S-Class', 1989);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (332, 'Volkswagen', 'R32', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (333, 'Toyota', 'Land Cruiser', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (334, 'Kia', 'Sportage', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (335, 'Dodge', 'Ram Van 3500', 2001);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (336, 'Suzuki', 'Sidekick', 1996);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (337, 'Chevrolet', 'Impala', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (338, 'Toyota', 'Tacoma', 1996);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (339, 'Jaguar', 'XJ Series', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (340, 'Subaru', 'Legacy', 2010);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (341, 'Mazda', 'MX-5', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (342, 'Toyota', 'Tacoma Xtra', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (343, 'Pontiac', '6000', 1990);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (344, 'Jeep', 'Grand Cherokee', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (345, 'Mercedes-Benz', 'M-Class', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (346, 'Honda', 'Element', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (347, 'Chevrolet', 'Suburban 2500', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (348, 'Dodge', 'Durango', 2003);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (349, 'Cadillac', 'DeVille', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (350, 'Subaru', 'Legacy', 2003);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (351, 'Audi', 'A8', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (352, 'Lincoln', 'Mark VII', 1992);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (353, 'Pontiac', 'Parisienne', 1986);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (354, 'Buick', 'Coachbuilder', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (355, 'Nissan', '240SX', 1997);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (356, 'Pontiac', 'Grand Prix', 1963);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (357, 'Chevrolet', 'Camaro', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (358, 'Chevrolet', 'Impala', 2001);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (359, 'Nissan', 'Altima', 2004);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (360, 'Dodge', 'Durango', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (361, 'Mercedes-Benz', 'CL-Class', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (362, 'Suzuki', 'Forenza', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (363, 'Nissan', 'Altima', 2010);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (364, 'Mercedes-Benz', 'SLK-Class', 2010);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (365, 'Mercury', 'Sable', 2002);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (366, 'GMC', 'Sonoma', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (367, 'Saab', '9000', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (368, 'Nissan', 'Maxima', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (369, 'Mitsubishi', 'RVR', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (370, 'Kia', 'Spectra', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (371, 'Maserati', 'Quattroporte', 2010);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (372, 'Mitsubishi', 'GTO', 1992);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (373, 'Honda', 'Ridgeline', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (374, 'Infiniti', 'QX', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (375, 'Pontiac', 'Trans Sport', 1997);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (376, 'Volvo', '850', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (377, 'Volkswagen', 'GTI', 1991);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (378, 'Audi', 'S5', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (379, 'Honda', 'Pilot', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (380, 'Chevrolet', 'Silverado', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (381, 'Pontiac', 'Daewoo Kalos', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (382, 'Audi', 'R8', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (383, 'Mazda', 'MX-6', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (384, 'Acura', 'Integra', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (385, 'Mercedes-Benz', 'C-Class', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (386, 'Jaguar', 'XK Series', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (387, 'Volkswagen', 'Cabriolet', 1988);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (388, 'Volkswagen', 'Touareg', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (389, 'Audi', 'S4', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (390, 'Mazda', 'B-Series', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (391, 'Mitsubishi', 'Eclipse', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (392, 'Chevrolet', 'Express 2500', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (393, 'Honda', 'Accord', 1986);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (394, 'Nissan', '370Z', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (395, 'Buick', 'Skylark', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (396, 'Porsche', '911', 2003);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (397, 'Mercedes-Benz', 'SL-Class', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (398, 'Acura', 'TSX', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (399, 'Chevrolet', 'Aveo', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (400, 'Honda', 'Passport', 1997);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (401, 'Pontiac', 'Firebird', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (402, 'Mercury', 'Grand Marquis', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (403, 'BMW', '1 Series', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (404, 'GMC', 'Vandura 1500', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (405, 'Infiniti', 'QX56', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (406, 'Nissan', 'Pathfinder', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (407, 'Dodge', 'Dynasty', 1992);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (408, 'Infiniti', 'QX', 2011);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (409, 'Isuzu', 'Space', 1992);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (410, 'Ford', 'Econoline E250', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (411, 'Daewoo', 'Nubira', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (412, 'Dodge', 'Grand Caravan', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (413, 'Mercury', 'Mystique', 1996);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (414, 'Ford', 'Bronco', 1990);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (415, 'Volkswagen', 'Jetta', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (416, 'Dodge', 'D250 Club', 1992);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (417, 'Chevrolet', 'Traverse', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (418, 'Ford', 'Ranger', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (419, 'Subaru', 'Justy', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (420, 'Acura', 'NSX', 2001);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (421, 'Ford', 'Econoline E150', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (422, 'Chevrolet', 'Cobalt', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (423, 'Chevrolet', 'Astro', 1998);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (424, 'Audi', 'S8', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (425, 'Mazda', 'RX-7', 1991);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (426, 'Pontiac', 'Solstice', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (427, 'Volvo', 'V70', 2002);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (428, 'Pontiac', 'G3', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (429, 'Ford', 'Mustang', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (430, 'Pontiac', 'Grand Am', 1990);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (431, 'Toyota', 'Tacoma', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (432, 'Infiniti', 'G37', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (433, 'Honda', 'Passport', 2001);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (434, 'Ford', 'E-Series', 1963);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (435, 'Ford', 'F350', 2003);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (436, 'Mercedes-Benz', '400SE', 1992);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (437, 'Dodge', 'Ram 3500', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (438, 'Jeep', 'Compass', 2010);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (439, 'Audi', 'A4', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (440, 'Chevrolet', 'Sportvan G20', 1992);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (441, 'Mercedes-Benz', 'SL-Class', 2001);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (442, 'BMW', '7 Series', 2003);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (443, 'Toyota', 'Matrix', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (444, 'Toyota', 'Prius Plug-in', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (445, 'Audi', 'Q7', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (446, 'Suzuki', 'Swift', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (447, 'Buick', 'Enclave', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (448, 'Honda', 'Odyssey', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (449, 'GMC', 'Savana 3500', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (450, 'Porsche', 'Carrera GT', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (451, 'Buick', 'Special', 1962);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (452, 'Audi', 'A6', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (453, 'Land Rover', 'LR2', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (454, 'Infiniti', 'G', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (455, 'GMC', 'Yukon XL 1500', 2013);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (456, 'Honda', 'Civic', 1988);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (457, 'Buick', 'Regal', 1998);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (458, 'Lexus', 'LS', 1997);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (459, 'Saturn', 'VUE', 2010);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (460, 'Volkswagen', 'Scirocco', 1986);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (461, 'Toyota', 'Highlander', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (462, 'Ford', 'E350', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (463, 'Ford', 'Explorer', 1997);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (464, 'Honda', 'CR-V', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (465, 'Mitsubishi', 'Montero Sport', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (466, 'Mitsubishi', 'Chariot', 1989);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (467, 'Mitsubishi', 'Starion', 1988);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (468, 'Chrysler', 'Crossfire', 2008);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (469, 'Oldsmobile', 'Alero', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (470, 'Chrysler', '300M', 2003);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (471, 'Ford', 'E-Series', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (472, 'Mitsubishi', 'Diamante', 1996);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (473, 'Pontiac', 'Grand Am', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (474, 'Jensen', 'Interceptor', 1966);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (475, 'GMC', 'Vandura 2500', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (476, 'Porsche', 'Boxster', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (477, 'Toyota', 'Matrix', 2010);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (478, 'Suzuki', 'SJ', 1985);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (479, 'Ford', 'E-Series', 1963);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (480, 'Chrysler', 'Sebring', 2007);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (481, 'Toyota', 'Avalon', 2009);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (482, 'Mitsubishi', 'Lancer Evolution', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (483, 'Austin', 'Mini', 1963);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (484, 'BMW', '525', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (485, 'Pontiac', 'Grand Prix', 2004);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (486, 'Buick', 'Roadmaster', 1994);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (487, 'Toyota', 'T100 Xtra', 1996);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (488, 'Jaguar', 'XF', 2010);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (489, 'Toyota', 'Celica', 1999);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (490, 'Lotus', 'Elise', 2010);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (491, 'Mazda', '929', 1989);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (492, 'GMC', 'Suburban 1500', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (493, 'GMC', 'Sierra 3500', 2012);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (494, 'Lincoln', 'LS', 2000);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (495, 'Chevrolet', '2500', 1993);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (496, 'Chevrolet', 'Cobalt', 2006);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (497, 'Plymouth', 'Acclaim', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (498, 'Volkswagen', 'Golf III', 1995);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (499, 'Hyundai', 'Accent', 2005);
insert into cars (OWNER_ID, BRAND, MODEL, CAR_YEAR) values (500, 'Infiniti', 'QX56', 2012);
